// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rillpkwxpdfyupissfka.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJpbGxwa3d4cGRmeXVwaXNzZmthIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyNjE2NzgsImV4cCI6MjA3MzgzNzY3OH0.dEUpfJlP9px50ME6LVn7wu4FQteH3EpfZ8oLfEKrT34";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});