// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ibwawbbsljnrpxaqrhtu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlid2F3YmJzbGpucnB4YXFyaHR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI4NzU0NTEsImV4cCI6MjA3ODQ1MTQ1MX0.jX7IA_uBWIWTp8dsfakIFPcKyVe7PLiNRHSvu8oM3Rg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
